# Generated by Django 5.2.1 on 2025-05-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0005_alter_book_image_url_alter_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
